"""Add merchandise table

Revision ID: 4cd097889b12
Revises: 1d80fe11db2a
Create Date: 2025-08-29 12:38:27.402339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd097889b12'
down_revision = '1d80fe11db2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_shirts_and_goodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tshirt_photo_url', sa.String(length=500), nullable=True),
    sa.Column('tshirt_form_url', sa.String(length=500), nullable=True),
    sa.Column('goodies_photo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_shirts_and_goodies')
    # ### end Alembic commands ###
